### ISSUE TITLE
As a mac user, I want to have the clinic header available in tabs

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#190] opened 2019-08-30 16:59 UTC
## Context
Currently when you are looking at information on a partner and you tab through the different options there is no display of the clinic header (clinic name, address, phone number).

## Process
Login and click on `View Lockbox Partner Details`. Go through the tabs (All activity, File a support request, Add cash to lockbox, Manage lockbox partner) - no clinic header is available in any of the views.

## Acceptance Criteria/Definition of Done
Have the clinic headers show up on each of the tabs for all partner clinics. 
![header](https://user-images.githubusercontent.com/5873894/64038502-cb7d7e00-cb1d-11e9-9d68-0c6705274d37.png)

## Resources
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/372540798
![missing_header](https://user-images.githubusercontent.com/5873894/64038105-e7345480-cb1c-11e9-8f10-5032192b34b0.png)

**Comment by BintLopez** [comment] 2019-09-15 07:51
Duplicate of https://github.com/MidwestAccessCoalition/lockbox_rails/issues/128

**Comment by misternu** [comment] 2019-09-22 21:26
resolved by #205

**Closed** 2019-10-27 21:35 UTC
