### ISSUE TITLE
Investigate and improve flaky test - support requests controller

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#531] opened 2020-12-13 22:48 UTC
## Context
The `spec/controllers/lockbox_partners/support_requests_controller_spec.rb` has been flaky. This should be investigated and improved upon. @scottyschup has suggested an improvement to make the call 10 times and taking an average. See:  

## Process
- Reproduce the flakiness
- Improve the test such that it no longer fails intermittently

## Acceptance Criteria/Definition of Done
- improvement to the test so that flaky failures no longer occur

**Comment by nsiwnf** [comment] 2021-01-10 22:42
@BintLopez @scottyschup  when was the last time this failed? Im having trouble finding an example in the test workflow

**Comment by nsiwnf** [comment] 2021-01-10 22:55
Unassigned myself - not sure I have enough context atm

**Comment by jel535s** [comment] 2021-01-11 00:04
As we were not able to reproduce this, @BintLopez may close this ticket out.

**Closed** 2021-03-28 23:39 UTC
Labels: MVP, WIP
