### ISSUE TITLE
Questions for stakeholders re UI

### ISSUE THREAD

**Issue by BintLopez** [MidwestAccessCoalition/lockbox_rails#61] opened 2019-05-05 21:19 UTC
This is the dashboard for MAC users in the lockbox....
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/5728859/57200389-0ba66880-6f51-11e9-815a-f206e8a7f6f9.png">

- What information is important for you to see at a glance on each lockbox's card in this dashboard? We are assuming that the 3 most recent lockbox actions are the most relevant pieces of information here

<img width="609" alt="image" src="https://user-images.githubusercontent.com/5728859/57200417-64760100-6f51-11e9-80f1-b991a2259706.png">

- How useful are notes to the lockbox partner?
- Would notes be useful in general for a support request?
- Is there typically a lot of back and forth between lockbox partner and MAC?

**Comment by jel535s** [comment] 2019-08-25 17:08
This seems to be a duplicate of https://github.com/MidwestAccessCoalition/lockbox_rails/issues/155

I've also added these questions into the documentation for issue #156

**Closed** 2019-12-22 22:31 UTC
Labels: duplicate
