### ISSUE TITLE
Off-boarding for users/partners

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#222] opened 2019-09-29 21:49 UTC
## Context
What are the instructions for off-boarding MAC users and partners?
Special permissions? Can anyone off board a partner? Do only "admins" off-board mac users? 

## Resources
N/A

**Comment by jel535s** [comment] 2019-10-27 21:57
duplicate of #154

**Closed by jel535s** 2019-10-27 21:57 UTC
Labels: design, question
