### ISSUE TITLE
As a mac user, when I'm on mobile I want to see my account settings and update things...

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#194] opened 2019-09-01 22:51 UTC
## Context
When mac user is on mobile, this is what they should see when they click on account settings

## Process
None

## Acceptance Criteria/Definition of Done
Mobile menu open when not on a specific partner page. The dark blue indicates the current page the user is on. In this instance, they've opened the menu from the main dashboard - https://invis.io/9EMYOUG7ZBA#/372542665_mobile_Menu_-_MAC_User_-from_Home-
- dark blue for `View all lockboxes` (aka page they are currently on)
- can update partner user's personal name + password (not email)

Mobile menu open when the user IS on a specific partner page. Dark blue indicates current page - https://invis.io/9EMYOUG7ZBA#/372542666_mobile_Menu_-_MAC_User_-lockbox_Specific-
- dark blue for `View all lockboxes` (aka page they are currently on)
- can update partner user's personal name + password (not email)

## Resources
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/374918390_dashboard_-_Partner_User_-menu_Open_Mobile-

Prior tickets: 
https://github.com/MidwestAccessCoalition/lockbox_rails/issues/134
https://github.com/MidwestAccessCoalition/lockbox_rails/issues/127

**Comment by rebeldroid12** [comment] 2019-09-08 14:36
@gujacq what does update password look like?

**Comment by jel535s** [comment] 2020-02-09 23:11
duplicate of #324

**Closed by jel535s** 2020-02-09 23:11 UTC
Labels: design
