### ISSUE TITLE
As a mac user, I want to see my account settings and update somethings....

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#195] opened 2019-09-01 22:54 UTC
## Context
When user is on desktop, this is what they should see when they click on account settings

## Process
None

## Acceptance Criteria/Definition of Done
When they navigate to settings: https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/371461199_dashboard_-_MAC_User_-menu_Open_-_Account_Settings-
- can update partner user's personal name + password (not email)

What edit name looks like: 
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/361595345_dashboard_-_MAC_User_-menu_Open-

What edit password looks like:
????

## Resources
Prior tickets: 
https://github.com/MidwestAccessCoalition/lockbox_rails/issues/134
https://github.com/MidwestAccessCoalition/lockbox_rails/issues/127

**Comment by rebeldroid12** [comment] 2019-09-08 14:37
@gujacq what does update password look like?

**Comment by jel535s** [comment] 2020-02-09 23:11
duplicate of #324

**Closed by jel535s** 2020-02-09 23:11 UTC
Labels: design
