### ISSUE TITLE
As a partner user, when I'm on mobile I want to see my account settings and update somethings

### ISSUE THREAD

**Issue by rebeldroid12** [MidwestAccessCoalition/lockbox_rails#193] opened 2019-09-01 22:43 UTC
## Context
When partner is on mobile, this is what they should see when they click on account settings

## Process
None

## Acceptance Criteria/Definition of Done
When partner clicks on settings this is the view: https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/374918390_dashboard_-_Partner_User_-menu_Open_Mobile-
- dark blue for `All Activity` (aka page they are currently on)
- can update partner user's personal name + password
- can update partner address/contact information

## Resources
https://projects.invisionapp.com/share/9EMYOUG7ZBA#/screens/374918390_dashboard_-_Partner_User_-menu_Open_Mobile-

Prior tickets: 
https://github.com/MidwestAccessCoalition/lockbox_rails/issues/134
https://github.com/MidwestAccessCoalition/lockbox_rails/issues/127

**Comment by rebeldroid12** [comment] 2019-09-08 14:34
@gujacq what does update password look like?

**Comment by rebeldroid12** [comment] 2019-09-08 14:35
@gujacq what does update partner info and update partner user name look like?

**Comment by rebeldroid12** [comment] 2019-09-08 14:38
What does the updates to partner look like on desktop? will need to create a ticket for that.

**Comment by jel535s** [comment] 2020-02-09 23:10
duplicate of #324

**Closed by jel535s** 2020-02-09 23:10 UTC
Labels: duplicate
